# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0134a6d77cb5aa6942b771ed799d34f669f05d0eb2fcd951a0643ca05e42975b1d08c84cf818140a4a1de3ca2d40bf945d4d1d4277270db386dbdf1433140ecf

test:
  secret_key_base: 3614302d84cdf9363c751c3845e4afe8ffe2ad891cca30d993a43f5ceb2a35e116049eaa79621346889856285dfe5b03e7d93d9a2400d0f91303c613132a64c3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
